sonar.projectKey=YOUR_GITHUB_USERNAME_online-exam-system
sonar.organization=YOUR_GITHUB_USERNAME
sonar.sources=exam_system
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
